/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a org.lxqt.global_key_shortcuts.client -c OrgLxqtActionClientAdaptor -i action_p.h -l GlobalKeyShortcut::ActionImpl /home/debian/Lxqt1.3/lxqt-globalkeyes/lxqt-globalkeys-1.3.0/obj-x86_64-linux-gnu/client/org.lxqt.global_key_shortcuts.client.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_LXQT_GLOBAL_KEY_SHORTCUTS_CLIENT_H
#define ORG_LXQT_GLOBAL_KEY_SHORTCUTS_CLIENT_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "action_p.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.lxqt.global_key_shortcuts.client
 */
class OrgLxqtActionClientAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.lxqt.global_key_shortcuts.client")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.lxqt.global_key_shortcuts.client\">\n"
"    <method name=\"activated\"/>\n"
"    <method name=\"shortcutChanged\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"oldShortcut\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"newShortcut\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    OrgLxqtActionClientAdaptor(GlobalKeyShortcut::ActionImpl *parent);
    virtual ~OrgLxqtActionClientAdaptor();

    inline GlobalKeyShortcut::ActionImpl *parent() const
    { return static_cast<GlobalKeyShortcut::ActionImpl *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activated();
    void shortcutChanged(const QString &oldShortcut, const QString &newShortcut);
Q_SIGNALS: // SIGNALS
};

#endif
