// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_lxqtsysstat.cpp"
#include "EWIEGA46WW/moc_lxqtsysstatcolours.cpp"
#include "EWIEGA46WW/moc_lxqtsysstatconfiguration.cpp"
