// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_batterywatchersettings.cpp"
#include "EWIEGA46WW/moc_idlenesswatchersettings.cpp"
#include "EWIEGA46WW/moc_lidwatchersettings.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_powerkeyssettings.cpp"
#include "EWIEGA46WW/moc_powermanagementsettings.cpp"
#include "VNU7RW3YIC/moc_iconproducer.cpp"
