// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_lxqtcpuload.cpp"
#include "EWIEGA46WW/moc_lxqtcpuloadconfiguration.cpp"
#include "EWIEGA46WW/moc_lxqtcpuloadplugin.cpp"
