// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_desktopswitch.cpp"
#include "EWIEGA46WW/moc_desktopswitchbutton.cpp"
#include "EWIEGA46WW/moc_desktopswitchconfiguration.cpp"
