/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -i /home/debian/Lxqt1.3/lxqt-globalkeyes/lxqt-globalkeys-1.3.0/daemon/meta_types.h -p org.lxqt.global_key_shortcuts.daemon /home/debian/Lxqt1.3/lxqt-globalkeyes/lxqt-globalkeys-1.3.0/obj-x86_64-linux-gnu/config/org.lxqt.global_key_shortcuts.daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "org.lxqt.global_key_shortcuts.daemon.h"

/*
 * Implementation of interface class OrgLxqtGlobal_key_shortcutsDaemonInterface
 */

OrgLxqtGlobal_key_shortcutsDaemonInterface::OrgLxqtGlobal_key_shortcutsDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgLxqtGlobal_key_shortcutsDaemonInterface::~OrgLxqtGlobal_key_shortcutsDaemonInterface()
{
}


#include "org.lxqt.global_key_shortcuts.daemon.moc"
