// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_lxqtsensors.cpp"
#include "EWIEGA46WW/moc_lxqtsensorsconfiguration.cpp"
#include "EWIEGA46WW/moc_lxqtsensorsplugin.cpp"
